apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: on-demand-gather-pvc
  namespace: openshift-insights
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2-csi
